spring:
  jackson:
    default-property-inclusion: non_null
  cloud:
    openfeign:
      oauth2:
        enabled: true
#       this would correspond to the id under security->oauth2->client->registration
        clientRegistrationId: twitch
      client:
        config:
          twitch-api:
            url: https://api.twitch.tv/helix
            loggerLevel: basic
            default-request-headers:
              Client-Id: "d2tyr1pjnjfyi9qhfl09pnozkgk4os"
  security:
    oauth2:
      client:
        registration:
          twitch:
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_post
            client-id: "d2tyr1pjnjfyi9qhfl09pnozkgk4os"
            client-secret: "nx3vgtfvyaepb7msmvm5eczdzpg2sy"
        provider:
          twitch:
            token-uri: https://id.twitch.tv/oauth2/token

  datasource:
    # same as the port specified in docker
    url: jdbc:mysql://${DATABASE_URL:localhost}:3306/twitch?createDatabaseIfNotExist=true
    # the username
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:secret}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      # always initialise the database when you launch, bad practice when app online
      # alternative : never
      mode: always
      schema-locations : "classpath:database-init.sql"

logging:
  level:
    org.apache.coyote.http11.Http11InputBuffer: DEBUG # Incoming HTTP requests
    com.laioffer.twitch.external.TwitchApiClient: DEBUG
    org.springframework.jdbc.core: DEBUG # SQL
